use crate::db::DiagnosticReport;
use crate::AppState;
use printpdf::*;
use std::fs::File;
use std::io::BufWriter;
use tauri::State;

#[tauri::command]
pub fn export_report_pdf(state: State<AppState>, report_id: String, output_path: String) -> Result<String, String> {
    let report = state.db.lock().unwrap().get_report(&report_id).map_err(|e| e.to_string())?;
    generate_pdf(&report, &output_path)?;
    Ok(output_path)
}

fn generate_pdf(report: &DiagnosticReport, path: &str) -> Result<(), String> {
    let (doc, page1, layer1) = PdfDocument::new(
        &report.title,
        Mm(210.0),
        Mm(297.0),
        "Layer 1",
    );
    let current_layer = doc.get_page(page1).get_layer(layer1);

    let font = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|e| e.to_string())?;
    let font_bold = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| e.to_string())?;

    let mut y = 280.0;

    current_layer.use_text("THORPE DIAGNOSTIC REPORT", 18.0, Mm(20.0), Mm(y), &font_bold);
    y -= 12.0;
    current_layer.use_text(&report.title, 12.0, Mm(20.0), Mm(y), &font);
    y -= 10.0;
    current_layer.use_text(&format!("Generated: {}", report.created_at), 9.0, Mm(20.0), Mm(y), &font);
    y -= 15.0;

    current_layer.use_text(&format!("Health Score: {}/100", report.health_score), 14.0, Mm(20.0), Mm(y), &font_bold);
    y -= 8.0;
    current_layer.use_text(&format!("Risk Level: {}", report.risk_level.to_uppercase()), 11.0, Mm(20.0), Mm(y), &font);
    y -= 15.0;

    current_layer.use_text("SUMMARY", 12.0, Mm(20.0), Mm(y), &font_bold);
    y -= 8.0;
    for line in wrap_text(&report.summary, 80) {
        current_layer.use_text(&line, 10.0, Mm(20.0), Mm(y), &font);
        y -= 6.0;
    }
    y -= 8.0;

    current_layer.use_text("PLAIN LANGUAGE EXPLANATION", 12.0, Mm(20.0), Mm(y), &font_bold);
    y -= 8.0;
    for line in wrap_text(&report.plain_language, 80) {
        if y < 20.0 { break; }
        current_layer.use_text(&line, 10.0, Mm(20.0), Mm(y), &font);
        y -= 6.0;
    }
    y -= 8.0;

    if y > 30.0 {
        current_layer.use_text("FINDINGS", 12.0, Mm(20.0), Mm(y), &font_bold);
        y -= 8.0;
        if let Ok(findings) = serde_json::from_str::<Vec<serde_json::Value>>(&report.findings) {
            for finding in findings.iter().take(5) {
                if y < 20.0 { break; }
                let title = finding["title"].as_str().unwrap_or("Unknown");
                let severity = finding["severity"].as_str().unwrap_or("unknown");
                current_layer.use_text(&format!("[{}] {}", severity.to_uppercase(), title), 10.0, Mm(25.0), Mm(y), &font);
                y -= 6.0;
            }
        }
    }

    y -= 10.0;
    if y > 15.0 {
        current_layer.use_text("---", 10.0, Mm(20.0), Mm(y), &font);
        y -= 6.0;
        current_layer.use_text("Generated by Thorpe — AI IT Support Platform", 8.0, Mm(20.0), Mm(y), &font);
        y -= 5.0;
        current_layer.use_text("https://thorpe.app", 8.0, Mm(20.0), Mm(y), &font);
    }

    let file = File::create(path).map_err(|e| format!("Failed to create PDF file: {}", e))?;
    let mut buf_writer = BufWriter::new(file);
    doc.save(&mut buf_writer).map_err(|e| format!("Failed to save PDF: {}", e))?;

    Ok(())
}

fn wrap_text(text: &str, max_chars: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if current.len() + word.len() + 1 > max_chars {
            if !current.is_empty() {
                lines.push(current.clone());
            }
            current = word.to_string();
        } else {
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(word);
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    lines
}
